---
all:
  hosts:
    devbox:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
      zerotier_member_ip_assignments:
        - 192.168.252.2
      zerotier_member_description: "devbox"
