---
- hosts: all
  become: yes
  vars_files:
    - /devbox/files/config/vars.yml
  tasks:
    - name: allow passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: add path /devbox/bin
      lineinfile:
        path: "/home/{{ username}}/.bashrc"
        line: export PATH=$PATH:/devbox/bin

    - name: update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: install default packages
      apt:
        pkg:
          - vim
          - mc
          - borgbackup
          - samba
          - nfs-kernel-server
          - python3
          - git
          - virtualbox-guest-dkms
          - virtualbox-guest-x11

- hosts: all
  become: yes
  vars:
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
  roles:
    - role: geerlingguy.postgresql

- hosts: all
  tasks:
    - name: install zsh
      apt:
        pkg: zsh
      become: true

    - name: Check if .oh-my-zsh exists
      stat:
        path: ~/.oh-my-zsh
      register: stat_oh_my_zsh_result

    - name: clone oh-my-zsh
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~/.oh-my-zsh
      when: not stat_oh_my_zsh_result.stat.exists

- hosts: all
  become: true
  tasks:
    - name: add zsh to user
      user:
        name: tlb
        shell: /usr/bin/zsh


- hosts: all
  become: true
  pre_tasks:
  - sysctl:
      name: fs.inotify.max_user_watches
      value: 524288
      state: present    
  roles:
    - role: gantsign.visual-studio-code
