---
- hosts: all
  become: true
  tasks:
    - name: fstab data dir
      lineinfile:
        path: /etc/fstab
        line: /dev/sdb1 /devbox btrfs nofail,noatime,compress-force=zstd:1


- hosts: all
  vars_files:
    - /devbox/files/config/vars.yml
  tasks:
    - name: symlink dot files 
      command: "/devbox/bin/symlink /devbox/files /home/{{ username }}"
      register: symlink
      changed_when: "'symlinked' in symlink.stdout"

    - name: install galaxy packages
      command: ansible-galaxy install {{ item }}
      register: galaxy
      changed_when: "'already installed' not in galaxy.stderr"
      with_items:
        - geerlingguy.postgresql
        - bertvv.samba

