---
- hosts: all
  become: true
  vars_files:
    - /devbox/files/config/vars.yml
  tasks:
    - name: fstab data dir
      lineinfile:
        path: /etc/fstab
        line: /dev/sdb1 /devbox btrfs nofail,noatime,compress-force=zstd:1

    - name: configure internal network
      copy:
        src: /devbox/files/config/01-internal-network.yaml
        dest: /etc/netplan/01-internal-network.yaml
      register: network

    - name: update internal network
      command: netplan apply
      when: network.changed

    - name: symlink
      include_tasks: symlink.yml
      with_items:
        - { src: /devbox/bin/mymotd, dest: /etc/profile.d/mymotd }
        - { src: /devbox/files/samba, dest: /etc/samba }

    - name: autostart create project tmpfile symlinks
      cron:
        job: /devbox/bin/tmp-symlinks
        special_time: reboot
        user: "{{ username }}"

    - name: wait for internet connection
      wait_for:
        host: 8.8.8.8
        port: 53

- hosts: all
  vars_files:
    - /devbox/files/config/vars.yml
  tasks:
    - name: symlink dot files 
      command: "/devbox/bin/symlink /devbox/files /home/{{ username }}"
      register: symlink
      changed_when: "'symlinked' in symlink.stdout"

    - name: install galaxy packages
      command: ansible-galaxy install {{ item }}
      register: galaxy
      changed_when: "'already installed' not in galaxy.stderr"
      with_items:
        - geerlingguy.postgresql
        - gantsign.visual-studio-code

